Fix compilation errors for fmt v11
The new version of Folly is dependent on fmt v11, which adds a few checks
that will break the build. This commit prevents the following error from
happening:

1. Error "'this' argument to member function 'format' has type 'const
    fmt::formatter<facebook::velox::exec::Spiller::Type>', but function
    is not marked const".
    The new fmt v11 forces the const check. To fix this error, the
    "const" keyword was added to the `format()` function declarations.

2. Error "error: static assertion failed due to requirement
    'formattable_char': Mixing character types is disallowed."
    The new fmt v11 added a check to see if the arguments of
    fmt::make_format_args() have mixing different character types (e.g.,
    char vs wchar_t or std::string vs folly::Range<const char*>). To fix
    this, we need to convert the folly::StringPiece to string.

These changes are backward compatible and work with the old fmt version.